
export default new Map([
["src/content/ai-architecture/01-johdanto.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F01-johdanto.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/02-1-api-wrappers.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F02-1-api-wrappers.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/02-2-rag.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F02-2-rag.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/02-3-agents.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F02-3-agents.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/02-5-multimodal.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F02-5-multimodal.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/02-4-finetuning.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F02-4-finetuning.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/03-infrastructure.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F03-infrastructure.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/02-6-hybrid.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F02-6-hybrid.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/04-design-principles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F04-design-principles.mdx&astroContentModuleFlag=true")],
["src/content/ai-architecture/05-reference-architectures.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fai-architecture%2F05-reference-architectures.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/01-hcd.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F01-hcd.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/03-interaction-design.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F03-interaction-design.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/02-visual-trends.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F02-visual-trends.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/04-accessibility.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F04-accessibility.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/06-modern-ui.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F06-modern-ui.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/05-performance.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F05-performance.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/07-ai-ux.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F07-ai-ux.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/08-ux-research.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F08-ux-research.mdx&astroContentModuleFlag=true")],
["src/content/ui-ux/09-tools.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fui-ux%2F09-tools.mdx&astroContentModuleFlag=true")]]);
		